CustomersManagementNaturalCustomersQuery <- "
SELECT [CustomerID]
,[PublicCode]
,[NationalCode]
, REPLACE(REPLACE([CustomerName], N'í', N'í'), N'ß', N'˜') As [CustomerName]
, REPLACE(REPLACE([CustomerTypeDes], N'í', N'í'), N'ß', N'˜') As [CustomerTypeDes]
,[IsActive]
,[CustomerType]
,[OldCustomerID]
,[initialDate]
,[EconomyActivityCode]
,[PostalCode]
, REPLACE(REPLACE([CityName], N'í', N'í'), N'ß', N'˜') As [CityName]
, REPLACE(REPLACE([StateName], N'í', N'í'), N'ß', N'˜') As [StateName]
, REPLACE(REPLACE([Address], N'í', N'í'), N'ß', N'˜') As [Address]
,[RegisterNumber]
, REPLACE(REPLACE([MiddleName], N'í', N'í'), N'ß', N'˜') As [MiddleName]
, REPLACE(REPLACE([RegisterCityName], N'í', N'í'), N'ß', N'˜') As [RegisterCityName]
FROM [CUSTOMERSERVER].[CustomersManagement].[dbo].[VI_Natural]"