FutureDimCustomersQuery <- "SELECT [ID]
,[CreationDate]
,[LastModificationDate]
,[CustomerID]
,[CustomerCode]
,[LogicalType]
,REPLACE(REPLACE([Name], N'í', N'í'), N'ß', N'˜') As [Name]
,REPLACE(REPLACE([FatherManager], N'í', N'í'), N'ß', N'˜') As [FatherManager]
,[NationalID]
,[RegPassNumber]
,REPLACE(REPLACE([Hometown], N'í', N'í'), N'ß', N'˜') As [Hometown]
,[Status]
,[Capital]
,[MaxPositionCount]
,REPLACE(REPLACE([Comments], N'í', N'í'), N'ß', N'˜') As [Comments]
,REPLACE(REPLACE([Account_OwnerName], N'í', N'í'), N'ß', N'˜') As [Account_OwnerName]
,[Account_Bank]
,[Account_Type]
,[Account_Number]
,REPLACE(REPLACE([Account_InquireResult], N'í', N'í'), N'ß', N'˜') As [Account_InquireResult]
,REPLACE(REPLACE([PersonalAccount_OwnerName], N'í', N'í'), N'ß', N'˜') As [PersonalAccount_OwnerName]
,[PersonalAccount_Bank]
,[PersonalAccount_Type]
,[PersonalAccount_Number]
,REPLACE(REPLACE([PersonalAccount_InquireResult], N'í', N'í'), N'ß', N'˜') As [PersonalAccount_InquireResult]
,[Kind_ID]
,REPLACE(REPLACE([Kind_Name], N'í', N'í'), N'ß', N'˜') As [Kind_Name]
,[Kind_Kind]
,[Kind_Comments]
,[SourceDatabase_ID]
FROM [Future_DM].[Future_Dim].[Customer]"